name: Go
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Copy file to linode
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          source: "connorjf.ssh"
          target: ${{ secrets.PATH }}
