name: Go
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Set up SSH key
        run: |
          export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          mkdir -p ~/.ssh
          echo ${{ secrets.LINDOE_SSH_KEY }} > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          scp -p ${{ secrets.PORT }} connorjf.ssh ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.PATH }}/
